import { build } from "vite";
import { fileURLToPath } from "node:url";
import path from "node:path";

const root = fileURLToPath(new URL("../", import.meta.url));

// 生成普通浏览器脚本，继续支持本地双击网页；关闭压缩以保留可读性。
await build({
  configFile: false,
  root,
  publicDir: false,
  build: {
    outDir: path.join(root, "js/vendor"),
    emptyOutDir: false,
    minify: false,
    lib: {
      entry: path.join(root, "scripts/three-entry.js"),
      name: "THREE",
      formats: ["iife"],
      fileName: () => "three.js",
    },
    rollupOptions: {
      output: {
        banner: "/* Three.js r160 project subset. MIT License: LICENSE.three.txt. Generated by npm run build:three. */",
      },
    },
  },
});
