// 只导出地图和牌具实际使用的接口；内部依赖由构建工具自动保留。
// 新增 THREE.xxx 调用时，在这里补上对应名称，再运行 npm run build:three。
export {
  BoxGeometry,
  BufferGeometry,
  CanvasTexture,
  Clock,
  DataTexture,
  DirectionalLight,
  DoubleSide,
  ExtrudeGeometry,
  Group,
  HemisphereLight,
  Line,
  LineBasicMaterial,
  MathUtils,
  Mesh,
  MeshPhysicalMaterial,
  MeshStandardMaterial,
  NearestFilter,
  NoColorSpace,
  OrthographicCamera,
  PerspectiveCamera,
  PlaneGeometry,
  RGBAFormat,
  Scene,
  Shape,
  SRGBColorSpace,
  Texture,
  TextureLoader,
  UnsignedByteType,
  Vector3,
  WebGLRenderer,
} from "three";
